apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xs6uifbvr-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xs6uifbvr-java-quarkus-gitops